
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          current_role: string | null;
          target_role: string | null;
          experience_level: 'entry' | 'mid' | 'senior' | null;
          industry: string | null;
          location: string | null;
          bio: string | null;
          weekly_practice_goal: number | null;
          target_score: number | null;
          focus_areas: string[] | null;
          target_companies: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          current_role?: string | null;
          target_role?: string | null;
          experience_level?: 'entry' | 'mid' | 'senior' | null;
          industry?: string | null;
          location?: string | null;
          bio?: string | null;
          weekly_practice_goal?: number | null;
          target_score?: number | null;
          focus_areas?: string[] | null;
          target_companies?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          current_role?: string | null;
          target_role?: string | null;
          experience_level?: 'entry' | 'mid' | 'senior' | null;
          industry?: string | null;
          location?: string | null;
          bio?: string | null;
          weekly_practice_goal?: number | null;
          target_score?: number | null;
          focus_areas?: string[] | null;
          target_companies?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      interview_sessions: {
        Row: {
          id: string;
          user_id: string;
          type: 'practice' | 'mock';
          title: string;
          job_description: string | null;
          industry: string | null;
          role: string | null;
          experience_level: string | null;
          difficulty: 'easy' | 'medium' | 'hard';
          duration: number;
          status: 'setup' | 'in_progress' | 'completed' | 'paused';
          overall_score: number | null;
          feedback: any | null;
          recording_url: string | null;
          scheduled_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'practice' | 'mock';
          title: string;
          job_description?: string | null;
          industry?: string | null;
          role?: string | null;
          experience_level?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard';
          duration: number;
          status?: 'setup' | 'in_progress' | 'completed' | 'paused';
          overall_score?: number | null;
          feedback?: any | null;
          recording_url?: string | null;
          scheduled_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'practice' | 'mock';
          title?: string;
          job_description?: string | null;
          industry?: string | null;
          role?: string | null;
          experience_level?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard';
          duration?: number;
          status?: 'setup' | 'in_progress' | 'completed' | 'paused';
          overall_score?: number | null;
          feedback?: any | null;
          recording_url?: string | null;
          scheduled_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      interview_questions: {
        Row: {
          id: string;
          session_id: string;
          question: string;
          category: 'behavioral' | 'technical' | 'situational' | 'general' | 'closing';
          difficulty: 'easy' | 'medium' | 'hard';
          expected_structure: string | null;
          tips: string | null;
          answer: string | null;
          score: number | null;
          feedback: any | null;
          time_taken: number | null;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          question: string;
          category: 'behavioral' | 'technical' | 'situational' | 'general' | 'closing';
          difficulty?: 'easy' | 'medium' | 'hard';
          expected_structure?: string | null;
          tips?: string | null;
          answer?: string | null;
          score?: number | null;
          feedback?: any | null;
          time_taken?: number | null;
          order_index: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          question?: string;
          category?: 'behavioral' | 'technical' | 'situational' | 'general' | 'closing';
          difficulty?: 'easy' | 'medium' | 'hard';
          expected_structure?: string | null;
          tips?: string | null;
          answer?: string | null;
          score?: number | null;
          feedback?: any | null;
          time_taken?: number | null;
          order_index?: number;
          created_at?: string;
        };
      };
      progress_tracking: {
        Row: {
          id: string;
          user_id: string;
          skill_area: string;
          current_score: number;
          target_score: number;
          sessions_completed: number;
          improvement_rate: number | null;
          last_practice: string | null;
          achievements: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          skill_area: string;
          current_score: number;
          target_score: number;
          sessions_completed?: number;
          improvement_rate?: number | null;
          last_practice?: string | null;
          achievements?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          skill_area?: string;
          current_score?: number;
          target_score?: number;
          sessions_completed?: number;
          improvement_rate?: number | null;
          last_practice?: string | null;
          achievements?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      question_bank: {
        Row: {
          id: string;
          question: string;
          category: 'behavioral' | 'technical' | 'situational' | 'general' | 'closing';
          difficulty: 'easy' | 'medium' | 'hard';
          industry: string | null;
          role_type: string | null;
          experience_level: 'entry' | 'mid' | 'senior' | null;
          expected_structure: string | null;
          tips: string | null;
          sample_answer: string | null;
          tags: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          question: string;
          category: 'behavioral' | 'technical' | 'situational' | 'general' | 'closing';
          difficulty?: 'easy' | 'medium' | 'hard';
          industry?: string | null;
          role_type?: string | null;
          experience_level?: 'entry' | 'mid' | 'senior' | null;
          expected_structure?: string | null;
          tips?: string | null;
          sample_answer?: string | null;
          tags?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          question?: string;
          category?: 'behavioral' | 'technical' | 'situational' | 'general' | 'closing';
          difficulty?: 'easy' | 'medium' | 'hard';
          industry?: string | null;
          role_type?: string | null;
          experience_level?: 'entry' | 'mid' | 'senior' | null;
          expected_structure?: string | null;
          tips?: string | null;
          sample_answer?: string | null;
          tags?: string[] | null;
          created_at?: string;
        };
      };
    };
  };
}
